version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:19.19.0.0
    container_name: orclcdb
    restart: unless-stopped
    ports:
      - "1521:1521"
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./init-app-user.sql:/opt/oracle/scripts/startup/init-app-user.sql:ro
    environment:
      ORACLE_PWD: "PassWord-123"
      ORACLE_SID: "ORCLCDB"
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 2047
        hard: 16384
      stack:
        soft: 10485760
        hard: 33554432
      memlock:
        soft: 3221225472
        hard: 3221225472
    networks:
      - default

  php-app:
    build:
      context: .
    container_name: php-app
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./client:/var/www/html/
    environment:
      DB_HOST: oracle
      DB_PORT: 1521
      DB_USER: my_app_user  # From the init-app-user.sql
      DB_PASSWORD: "my_secure_password"  # From the init-app-user.sql
      DB_NAME: ORCLPDB1
    networks:
      - default

    depends_on:
      - oracle
